name: Deploy to Amazon S3 bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Build website
        run: hugo --minify

      # - name: Sync files to S3
      #   run: aws s3 sync ./public s3://${{ secrets.S3_BUCKET }} --delete

      # - name: Invalidate CloudFront Distribution
      #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Hugo deploy static site to S3 bucket and invalidate Cloudfront cache
        run: hugo deploy --maxDeletes -1 --invalidateCDN

